//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmashSoft.Plataforma {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", ConfigurationName="Plataforma.SmashSoftPlataformaService")]
    public interface SmashSoftPlataformaService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.smashsoft.pucp.edu.pe/SmashSoftPlataformaService/listarPlataforma" +
            "sTodasRequest", ReplyAction="http://services.smashsoft.pucp.edu.pe/SmashSoftPlataformaService/listarPlataforma" +
            "sTodasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmashSoft.Plataforma.listarPlataformasTodasResponse listarPlataformasTodas(SmashSoft.Plataforma.listarPlataformasTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.smashsoft.pucp.edu.pe/SmashSoftPlataformaService/listarPlataforma" +
            "sTodasRequest", ReplyAction="http://services.smashsoft.pucp.edu.pe/SmashSoftPlataformaService/listarPlataforma" +
            "sTodasResponse")]
        System.Threading.Tasks.Task<SmashSoft.Plataforma.listarPlataformasTodasResponse> listarPlataformasTodasAsync(SmashSoft.Plataforma.listarPlataformasTodasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/")]
    public partial class plataforma : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idPlataformaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idPlataforma {
            get {
                return this.idPlataformaField;
            }
            set {
                this.idPlataformaField = value;
                this.RaisePropertyChanged("idPlataforma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPlataformasTodas", WrapperNamespace="http://services.smashsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPlataformasTodasRequest {
        
        public listarPlataformasTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPlataformasTodasResponse", WrapperNamespace="http://services.smashsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPlataformasTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SmashSoft.Plataforma.plataforma[] @return;
        
        public listarPlataformasTodasResponse() {
        }
        
        public listarPlataformasTodasResponse(SmashSoft.Plataforma.plataforma[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmashSoftPlataformaServiceChannel : SmashSoft.Plataforma.SmashSoftPlataformaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmashSoftPlataformaServiceClient : System.ServiceModel.ClientBase<SmashSoft.Plataforma.SmashSoftPlataformaService>, SmashSoft.Plataforma.SmashSoftPlataformaService {
        
        public SmashSoftPlataformaServiceClient() {
        }
        
        public SmashSoftPlataformaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmashSoftPlataformaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmashSoftPlataformaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmashSoftPlataformaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmashSoft.Plataforma.listarPlataformasTodasResponse SmashSoft.Plataforma.SmashSoftPlataformaService.listarPlataformasTodas(SmashSoft.Plataforma.listarPlataformasTodasRequest request) {
            return base.Channel.listarPlataformasTodas(request);
        }
        
        public SmashSoft.Plataforma.plataforma[] listarPlataformasTodas() {
            SmashSoft.Plataforma.listarPlataformasTodasRequest inValue = new SmashSoft.Plataforma.listarPlataformasTodasRequest();
            SmashSoft.Plataforma.listarPlataformasTodasResponse retVal = ((SmashSoft.Plataforma.SmashSoftPlataformaService)(this)).listarPlataformasTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmashSoft.Plataforma.listarPlataformasTodasResponse> SmashSoft.Plataforma.SmashSoftPlataformaService.listarPlataformasTodasAsync(SmashSoft.Plataforma.listarPlataformasTodasRequest request) {
            return base.Channel.listarPlataformasTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmashSoft.Plataforma.listarPlataformasTodasResponse> listarPlataformasTodasAsync() {
            SmashSoft.Plataforma.listarPlataformasTodasRequest inValue = new SmashSoft.Plataforma.listarPlataformasTodasRequest();
            return ((SmashSoft.Plataforma.SmashSoftPlataformaService)(this)).listarPlataformasTodasAsync(inValue);
        }
    }
}
