//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmashSoft.UniversoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", ConfigurationName="UniversoService.SmashSoftUniversoService")]
    public interface SmashSoftUniversoService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.smashsoft.pucp.edu.pe/SmashSoftUniversoService/listarUniversosPor" +
            "NombreRequest", ReplyAction="http://services.smashsoft.pucp.edu.pe/SmashSoftUniversoService/listarUniversosPor" +
            "NombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmashSoft.UniversoService.listarUniversosPorNombreResponse listarUniversosPorNombre(SmashSoft.UniversoService.listarUniversosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.smashsoft.pucp.edu.pe/SmashSoftUniversoService/listarUniversosPor" +
            "NombreRequest", ReplyAction="http://services.smashsoft.pucp.edu.pe/SmashSoftUniversoService/listarUniversosPor" +
            "NombreResponse")]
        System.Threading.Tasks.Task<SmashSoft.UniversoService.listarUniversosPorNombreResponse> listarUniversosPorNombreAsync(SmashSoft.UniversoService.listarUniversosPorNombreRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/")]
    public partial class universo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idUniversoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idUniverso {
            get {
                return this.idUniversoField;
            }
            set {
                this.idUniversoField = value;
                this.RaisePropertyChanged("idUniverso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUniversosPorNombre", WrapperNamespace="http://services.smashsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUniversosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarUniversosPorNombreRequest() {
        }
        
        public listarUniversosPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUniversosPorNombreResponse", WrapperNamespace="http://services.smashsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUniversosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SmashSoft.UniversoService.universo[] @return;
        
        public listarUniversosPorNombreResponse() {
        }
        
        public listarUniversosPorNombreResponse(SmashSoft.UniversoService.universo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmashSoftUniversoServiceChannel : SmashSoft.UniversoService.SmashSoftUniversoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmashSoftUniversoServiceClient : System.ServiceModel.ClientBase<SmashSoft.UniversoService.SmashSoftUniversoService>, SmashSoft.UniversoService.SmashSoftUniversoService {
        
        public SmashSoftUniversoServiceClient() {
        }
        
        public SmashSoftUniversoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmashSoftUniversoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmashSoftUniversoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmashSoftUniversoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmashSoft.UniversoService.listarUniversosPorNombreResponse SmashSoft.UniversoService.SmashSoftUniversoService.listarUniversosPorNombre(SmashSoft.UniversoService.listarUniversosPorNombreRequest request) {
            return base.Channel.listarUniversosPorNombre(request);
        }
        
        public SmashSoft.UniversoService.universo[] listarUniversosPorNombre(string nombre) {
            SmashSoft.UniversoService.listarUniversosPorNombreRequest inValue = new SmashSoft.UniversoService.listarUniversosPorNombreRequest();
            inValue.nombre = nombre;
            SmashSoft.UniversoService.listarUniversosPorNombreResponse retVal = ((SmashSoft.UniversoService.SmashSoftUniversoService)(this)).listarUniversosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmashSoft.UniversoService.listarUniversosPorNombreResponse> SmashSoft.UniversoService.SmashSoftUniversoService.listarUniversosPorNombreAsync(SmashSoft.UniversoService.listarUniversosPorNombreRequest request) {
            return base.Channel.listarUniversosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmashSoft.UniversoService.listarUniversosPorNombreResponse> listarUniversosPorNombreAsync(string nombre) {
            SmashSoft.UniversoService.listarUniversosPorNombreRequest inValue = new SmashSoft.UniversoService.listarUniversosPorNombreRequest();
            inValue.nombre = nombre;
            return ((SmashSoft.UniversoService.SmashSoftUniversoService)(this)).listarUniversosPorNombreAsync(inValue);
        }
    }
}
